version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

  ui:
    image: node:lts
    container_name: genieacs-ui
    working_dir: /app
    command: sh -c "test -d node_modules || npm ci --omit=dev && node bin/genieacs-ui"
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      GENIEACS_DEBUG_FILE: /app/genieacs-debug.yaml
      GENIEACS_UI_JWT_SECRET: change-this-secret
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./:/app
      - ui_node_modules:/app/node_modules

  cwmp:
    image: node:lts
    container_name: genieacs-cwmp
    working_dir: /app
    command: sh -c "test -d node_modules || npm ci --omit=dev && node bin/genieacs-cwmp"
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      GENIEACS_DEBUG_FILE: /app/genieacs-debug.yaml
      GENIEACS_EXT_DIR: /app/ext
      GENIEACS_CWMP_INTERFACE: 0.0.0.0
      NODE_ENV: production
    ports:
      - "7547:7547"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./ext:/app/ext:ro
      - cwmp_node_modules:/app/node_modules

  nbi:
    image: node:lts
    container_name: genieacs-nbi
    working_dir: /app
    command: sh -c "test -d node_modules || npm ci --omit=dev && node bin/genieacs-nbi"
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      GENIEACS_NBI_INTERFACE: 0.0.0.0
      NODE_ENV: production
    ports:
      - "7557:7557"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./:/app
      - nbi_node_modules:/app/node_modules

  fs:
    image: node:lts
    container_name: genieacs-fs
    working_dir: /app
    command: sh -c "test -d node_modules || npm ci --omit=dev && node bin/genieacs-fs"
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      NODE_ENV: production
    ports:
      - "7567:7567"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./:/app
      - fs_node_modules:/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  ui_node_modules:
  cwmp_node_modules:
  nbi_node_modules:
  fs_node_modules:
