version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  # Build a single image from this repository and reuse it for all GenieACS services
  genieacs-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: genieacs-base
    # set working directory so process.cwd() resolves to the project root
    working_dir: /app
    command: ["sleep", "infinity"]

  ui:
    image: genieacs-base
    container_name: genieacs-ui
    working_dir: /app
    command: sh -c "npm install && node bin/genieacs-ui"
    ports:
      - "3000:3000"
    environment:
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      - GENIEACS_DEBUG_FILE=/app/genieacs-debug.yaml
      - GENIEACS_UI_JWT_SECRET=change-this-secret
    depends_on:
      - mongodb

  cwmp:
    image: genieacs-base
    container_name: genieacs-cwmp
    working_dir: /app
    command: sh -c "npm install && node bin/genieacs-cwmp"
    ports:
      - "7547:7547"
    environment:
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      - GENIEACS_DEBUG_FILE=/app/genieacs-debug.yaml
      - GENIEACS_EXT_DIR=/opt/genieacs/ext
      - GENIEACS_CWMP_INTERFACE=0.0.0.0
    volumes:
      - ./ext:/opt/genieacs/ext
    depends_on:
      - mongodb

  nbi:
    image: genieacs-base
    container_name: genieacs-nbi
    working_dir: /app
    command: sh -c "npm install && node bin/genieacs-nbi"
    ports:
      - "7557:7557"
    environment:
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      - GENIEACS_NBI_INTERFACE=0.0.0.0
    depends_on:
      - mongodb

  fs:
    image: genieacs-base
    container_name: genieacs-fs
    working_dir: /app
    command: sh -c "npm install && node bin/genieacs-fs"
    ports:
      - "7567:7567"
    environment:
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://root:password@mongodb:27017/genieacs?authSource=admin
    depends_on:
      - mongodb

networks:
  default:
    driver: bridge
