version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017"
    volumes:
      - ./mongo-data:/data/db
    # Pin the MongoDB container to a static address on the internal network

  # Build an image from the repository once and reuse it for all GenieACS services
  genieacs-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: genieacs-base
    command: ["sleep", "infinity"]

  # GenieACS UI service listening on all interfaces with a fixed IP
  ui:
    image: genieacs-base
    working_dir: /app
    command: sh -c "npm install && node bin/genieacs-ui"
    ports:
      - "3000"
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      GENIEACS_DEBUG_FILE: /app/genieacs-debug.yaml
      GENIEACS_UI_JWT_SECRET: change-this-secret
      GENIEACS_UI_INTERFACE: 0.0.0.0
    depends_on:
      - mongodb

  # GenieACS CWMP service (ACS server) with extensions directory mounted
  cwmp:
    image: genieacs-base
    working_dir: /app
    command: sh -c "npm install && node bin/genieacs-cwmp"
    ports:
      - "7547"
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      GENIEACS_DEBUG_FILE: /app/genieacs-debug.yaml
      GENIEACS_EXT_DIR: /opt/genieacs/ext
      GENIEACS_CWMP_INTERFACE: 0.0.0.0
    volumes:
      - ./ext:/opt/genieacs/ext
    depends_on:
      - mongodb

  # GenieACS NBI service for API access
  nbi:
    image: genieacs-base
    working_dir: /app
    command: sh -c "npm install && node bin/genieacs-nbi"
    ports:
      - "7557"
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      GENIEACS_NBI_INTERFACE: 0.0.0.0
    depends_on:
      - mongodb

  # GenieACS File Server service
  fs:
    image: genieacs-base
    working_dir: /app
    command: sh -c "npm install && node bin/genieacs-fs"
    ports:
      - "7567"
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/genieacs?authSource=admin
      GENIEACS_FS_INTERFACE: 0.0.0.0
    depends_on:
      - mongodb

networks:
  genie-net:
    driver: bridge